### ISSUE TITLE
Arrays/Noble Integer problem

### ISSUE THREAD

**Issue by akshayarise** [royalpranjal/Interview-Bit#2]
hi pranjal,
 In array section you didn't mention the code for "noble integer problem". please give that too as I am not able to code that problem.

**Comment by royalpranjal** [comment]
Hi Akshay
The problem has now been solved. Please find the [solution here](https://github.com/royalpranjal/Interview-Bit/blob/master/Arrays/Noble%20Integer.cpp)

**Comment by akshayarise** [comment]
thanks @royalpranjal
