### ISSUE TITLE
fail on this test case

### ISSUE THREAD

**Issue by pkdhirasaria** [royalpranjal/Interview-Bit#24]
for string Ab3bd the output should be 2, i.e. string shoule be Adb3bdA, but your programs gives 4.
FOR THIS :
https://github.com/royalpranjal/Interview-Bit/blob/master/Strings/Minimum%20Characters%20required%20to%20make%20a%20String%20Palindromic.cpp

**Comment by me-ydv-5** [comment]
I guess you misinterpreted the question. Look again at your version of string, you've added an extra A at the end (index 6) and a 'd' at index 1, which is not there in the input string.

You need to add at the beginning. To make it a palindrome, you remove each character from the end and see if it makes a palindrome. For the input, Ab3bd, we remove b3bd from the end and then we get the palindrome 'A', so we need to add four characters at the beginning to make the input string a palindrome.

Hope this clarifies your query.
