### ISSUE TITLE
getting the solutions

### ISSUE THREAD

**Issue by vaibhavsood** [royalpranjal/Interview-Bit#9]
Hi, can you tell me how you downloaded your solutions from Interviewbit? Did you scrape the website or use any automated method to get your solutions?

**Comment by royalpranjal** [comment]
Hi

These solutions are my own & not downloaded/scrapped from any website.

**Comment by vaibhavsood** [comment]
i understand, my question is how did you download your own solutions from the interviewbit website, manually or via scripts?
